version: 2

workflows:
  version: 2
  build:
    jobs:
      - bla

jobs:
   bla:
     docker:
       - image: circleci/python:3-stretch-browsers
     steps:
       - checkout
       - run: echo "hello world"

